/* variable for aspect option labels, values and array of snags associated to them*/
const aspects = {
    internalDoors: [
        { value: 'doorclearance', label: 'Min 10mm max 25mm clearance between unfinished floor and bottom of door' },
        { value: 'doorcatching', label: 'Doors open/close without catching in frames' },
        { value: 'handlecatching', label: 'Door handles/latches open/close without catching' },
        { value: 'handlessecured', label: 'Door handles/latches secured and free of cosmetic damage when viewed from a distance of 1m' },
        { value: 'cosmeticdamage', label: 'Doors free of cosmetic damage when viewed from a distance of 1m' },
    ],
    externalDoors: [
        { value: 'framedamage', label: 'Door and frame free of damage' },
        { value: 'presentfixtures', label: 'All fixtures and fittings present and free of excessive cosmetic damage when viewed from a distance of 1m' },
        { value: 'gasketspresent', label: 'All sealing gaskets present to all sides of door/frame and free of damage' },
        { value: 'structuralimpact', label: 'All doors open/close without impacting structure or internal/external features/fittings' },
    ],
    glazing: [
        { value: 'noscratches', label: 'Glass viewed from 2m is free of fine scratches no longer than 25mm' },
        { value: 'nobubbles', label: 'Glass viewed from 2m is free of bubbles, blisters, hairlines or blobs' },
        { value: 'noparticles', label: 'Glass viewed from 2m is free of minute particles' },
        { value: 'windowscloseopen', label: 'Windows open and close freely' },
        { value: 'gasketsinplace', label: 'Sealing gaskets inplace' },
        { value: 'keyslocks', label: 'Keys present and lock units' },
    ],
    internalWalls: [
        { value: 'nodeviation', label: 'Free of excessive deviation over 450mm straight edge' },
        { value: 'uniformsurfaces', label: 'Surfaces reasonably uniform with only minor textural differences when view from 2m' },
        { value: 'nocracks', label: 'Free of cracks wider than 2mm' },
        { value: 'jointingtape', label: 'Jointing tape fully covered and not visually obtrusive' },
        { value: 'skirtingcracks', label: 'Skirtings free of cracks wider than 2mm' },
        { value: 'nomould', label: 'All surfaces free of mould or signs of condensation' },
    ],
    floorsAndStairs: [
        { value: 'flooruniform', label: 'Ground floor finished with uniform screed layer, free of excessive cracking' },
        { value: 'floordeviation', label: 'All flooring to be free of excessive deviation' },
        { value: 'floormovement', label: 'All upstairs floor/stair boarding to be free of excessive movement or noise' },
        { value: 'securehandrails', label: 'All handrails/ballustrades secure and free of excessive movement' },
        { value: 'handraildamage', label: 'All handrails free of excessive cosmetic damage when viewed from a distance of 1m' },
        { value: 'handrailsuniform', label: 'All handrails/ballustrades have uniform cosmetic finish when viewed from a distance of 1m' },
        { value: 'pavingdamage', label: 'Paving stones level and free of damage/cracks' },
    ],
    electrics: [
        { value: 'switchessecure', label: 'Faceplates and switches are secure to backbox and free of movement' },
        { value: 'socketsworking', label: 'All wall sockets and light switches working (socket tester and test bulb)' },
        { value: 'noswitchgaps', label: 'Faceplates and switches are free of excessive gaps' },
        { value: 'switcheslevel', label: 'Faceplates and switches are visually level' },
        { value: 'alarmsworking', label: 'Smoke/Heat alarms present and working' },
        { value: 'fttpinstalled', label: 'FTTP modems installed' },
        { value: 'consumerunitaccess', label: 'Consumer unit accessible and labelled' },
    ],
    plumbing: [
        { value: 'plumbingfixtures', label: 'All plumbing fixtures and fittings free of cracks/chips/scraches and excessive cosmetic imperfections' },
        { value: 'tapsmovement', label: 'All taps free of movement' },
        { value: 'tapleaks', label: 'All taps free of drips/leaks' },
        { value: 'tapmarks', label: 'All taps correctly marked for hot and cold' },
        { value: 'tappressure', label: 'All taps working with reasonable pressure' },
        { value: 'tapseals', label: 'All taps sealed correctly' },
        { value: 'basinmovement', label: 'All basins and pedestal free of movement' },
        { value: 'basinseals', label: 'All basins and pedestal seals intact' },
        { value: 'integratedplugs', label: 'All integrated plugs present and functional' },
        { value: 'toiletmovement', label: 'All toilets and cisterns free of movement' },
        { value: 'toiletseatsecure', label: 'All toilet seats secure and free of damage' },
        { value: 'toiletflushing', label: 'All toilets flushing and draining' },
        { value: 'flushplatesecure', label: 'All integrated flushplates secure and sealed' },
        { value: 'showerscreensealed', label: 'Showerscreen seals present' },
        { value: 'showerscreendamage', label: 'Showerscreen free of damage' },
        { value: 'bathmovement', label: 'Baths free of excessive movement' },
    ],
    worktopsAndUnits: [
        { value: 'surfacesdamage', label: 'All surfaces free of excessive cosmetic damage when viewed from a distance of 0.5m' },
        { value: 'worktopsealsintact', label: 'All seals to worktops, joins and splashback intact' },
        { value: 'edgeveneerspresent', label: 'All edge veneers and joining strips present and secure' },
        { value: 'unitsnotcatching', label: 'All units opening/closing without catching' },
        { value: 'accessibleunits', label: 'All units reasonably accessible without obstruction when open' },
    ],
    appliances: [
        { value: 'appliancesnodamage', label: 'Supplied appliances free of excessive cosmetic damage when view from a distance of 0.5m' },
        { value: 'applianceelectrics', label: 'Appliances have electrical supply and are observed as reasonably working' },
        { value: 'appliancesgas', label: 'Appliances have gas supply and tested as reasonably working' },
    ],
    heatingSystem: [
        { value: 'boilerworking', label: 'Boiler turned on and is without error codes' },
        { value: 'systempressure', label: 'System pressure is adequate' },
        { value: 'thermostatswork', label: 'All thermostats turn on and send call for heat' },
        { value: 'radiatorswork', label: 'All radiators observed to be heating up' },
        { value: 'radiatortrvsecure', label: 'All radiator TRVs present and secure' },
        { value: 'radiatorleaks', label: 'All radiators free of leaks' },
        { value: 'radiatordamage', label: 'All radiators to be free of large dents with a consistent finish when viewed from a distance of 1m' },
        { value: 'radiatorbrackets', label: 'All radiator brackets free of excessive movement' },
        { value: 'pipingcosmetics', label: 'All piping finished to a good cosmetic standard, including all wall holes to be gromitted' },
    ],
}

export default aspects;