const locationAspects = { 
    hallway: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    bathRooms: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'plumbing', label: 'Plumbing'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    kitchen: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'plumbing', label: 'Plumbing'},
        { value: 'worktopsandunits', label: 'Worktops and units'},
        { value: 'appliances', label: 'Appliances'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    bedRooms: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    garage: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'externaldoors', label: 'External Doors' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
    ],
    livingRoom: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    wc: [
        { value: 'internaldoors', label: 'Internal Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'internalwalls', label: 'Internal Walls' },
        { value: 'floorsandstairs', label: 'Floors and stairs' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'plumbing', label: 'Plumbing'},
        { value: 'heatingsystem', label: 'Heating system'},
    ],
    external: [
        { value: 'externaldoors', label: 'External Doors' },
        { value: 'glazing', label: 'Glazing' },
        { value: 'electrics', label: 'Electrics'},
        { value: 'plumbing', label: 'Plumbing'},
    ],
    stairs: [
        { value: 'floorsandstairs', label: 'Floors and Stairs' },
        { value: 'electrics', label: 'Electrics'},
    ],
}

export default locationAspects;